/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthRouteRouteImport } from './routes/_unauth/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as UnauthSignupRouteImport } from './routes/_unauth/signup'
import { Route as UnauthLoginRouteImport } from './routes/_unauth/login'
import { Route as AuthWorkflowsRouteImport } from './routes/_auth/workflows'
import { Route as AuthSettingsRouteImport } from './routes/_auth/settings'
import { Route as AuthReviewsRouteImport } from './routes/_auth/reviews'
import { Route as AuthMattersRouteImport } from './routes/_auth/matters'
import { Route as AuthDocumentsRouteImport } from './routes/_auth/documents'
import { Route as AuthContractsRouteImport } from './routes/_auth/contracts'
import { Route as AuthClientsRouteImport } from './routes/_auth/clients'
import { Route as AuthChatRouteImport } from './routes/_auth/chat'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known/$'
import { Route as marketingAboutRouteImport } from './routes/(marketing)/about'
import { Route as AuthReviewsIdRouteImport } from './routes/_auth/reviews.$id'
import { Route as AuthMattersIdRouteImport } from './routes/_auth/matters_.$id'
import { Route as AuthContractsIdRouteImport } from './routes/_auth/contracts_.$id'

const UnauthRouteRoute = UnauthRouteRouteImport.update({
  id: '/_unauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthSignupRoute = UnauthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const UnauthLoginRoute = UnauthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const AuthWorkflowsRoute = AuthWorkflowsRouteImport.update({
  id: '/workflows',
  path: '/workflows',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReviewsRoute = AuthReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMattersRoute = AuthMattersRouteImport.update({
  id: '/matters',
  path: '/matters',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDocumentsRoute = AuthDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthContractsRoute = AuthContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthClientsRoute = AuthClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthChatRoute = AuthChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AuthRouteRoute,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingAboutRoute = marketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => marketingRouteRoute,
} as any)
const AuthReviewsIdRoute = AuthReviewsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthReviewsRoute,
} as any)
const AuthMattersIdRoute = AuthMattersIdRouteImport.update({
  id: '/matters_/$id',
  path: '/matters/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthContractsIdRoute = AuthContractsIdRouteImport.update({
  id: '/contracts_/$id',
  path: '/contracts/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/about': typeof marketingAboutRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/chat': typeof AuthChatRoute
  '/clients': typeof AuthClientsRoute
  '/contracts': typeof AuthContractsRoute
  '/documents': typeof AuthDocumentsRoute
  '/matters': typeof AuthMattersRoute
  '/reviews': typeof AuthReviewsRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/workflows': typeof AuthWorkflowsRoute
  '/login': typeof UnauthLoginRoute
  '/signup': typeof UnauthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/contracts/$id': typeof AuthContractsIdRoute
  '/matters/$id': typeof AuthMattersIdRoute
  '/reviews/$id': typeof AuthReviewsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/about': typeof marketingAboutRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/chat': typeof AuthChatRoute
  '/clients': typeof AuthClientsRoute
  '/contracts': typeof AuthContractsRoute
  '/documents': typeof AuthDocumentsRoute
  '/matters': typeof AuthMattersRoute
  '/reviews': typeof AuthReviewsRouteWithChildren
  '/settings': typeof AuthSettingsRoute
  '/workflows': typeof AuthWorkflowsRoute
  '/login': typeof UnauthLoginRoute
  '/signup': typeof UnauthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/contracts/$id': typeof AuthContractsIdRoute
  '/matters/$id': typeof AuthMattersIdRoute
  '/reviews/$id': typeof AuthReviewsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_unauth': typeof UnauthRouteRouteWithChildren
  '/(marketing)/about': typeof marketingAboutRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/_auth/chat': typeof AuthChatRoute
  '/_auth/clients': typeof AuthClientsRoute
  '/_auth/contracts': typeof AuthContractsRoute
  '/_auth/documents': typeof AuthDocumentsRoute
  '/_auth/matters': typeof AuthMattersRoute
  '/_auth/reviews': typeof AuthReviewsRouteWithChildren
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/workflows': typeof AuthWorkflowsRoute
  '/_unauth/login': typeof UnauthLoginRoute
  '/_unauth/signup': typeof UnauthSignupRoute
  '/api/$': typeof ApiSplatRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/_auth/contracts_/$id': typeof AuthContractsIdRoute
  '/_auth/matters_/$id': typeof AuthMattersIdRoute
  '/_auth/reviews/$id': typeof AuthReviewsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/.well-known/$'
    | '/chat'
    | '/clients'
    | '/contracts'
    | '/documents'
    | '/matters'
    | '/reviews'
    | '/settings'
    | '/workflows'
    | '/login'
    | '/signup'
    | '/api/$'
    | '/contracts/$id'
    | '/matters/$id'
    | '/reviews/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/.well-known/$'
    | '/chat'
    | '/clients'
    | '/contracts'
    | '/documents'
    | '/matters'
    | '/reviews'
    | '/settings'
    | '/workflows'
    | '/login'
    | '/signup'
    | '/api/$'
    | '/contracts/$id'
    | '/matters/$id'
    | '/reviews/$id'
  id:
    | '__root__'
    | '/(marketing)'
    | '/_auth'
    | '/_unauth'
    | '/(marketing)/about'
    | '/.well-known/$'
    | '/_auth/chat'
    | '/_auth/clients'
    | '/_auth/contracts'
    | '/_auth/documents'
    | '/_auth/matters'
    | '/_auth/reviews'
    | '/_auth/settings'
    | '/_auth/workflows'
    | '/_unauth/login'
    | '/_unauth/signup'
    | '/api/$'
    | '/(marketing)/'
    | '/_auth/contracts_/$id'
    | '/_auth/matters_/$id'
    | '/_auth/reviews/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  UnauthRouteRoute: typeof UnauthRouteRouteWithChildren
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauth': {
      id: '/_unauth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth/signup': {
      id: '/_unauth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthSignupRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_unauth/login': {
      id: '/_unauth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthLoginRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_auth/workflows': {
      id: '/_auth/workflows'
      path: '/workflows'
      fullPath: '/workflows'
      preLoaderRoute: typeof AuthWorkflowsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reviews': {
      id: '/_auth/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof AuthReviewsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/matters': {
      id: '/_auth/matters'
      path: '/matters'
      fullPath: '/matters'
      preLoaderRoute: typeof AuthMattersRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/documents': {
      id: '/_auth/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof AuthDocumentsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/contracts': {
      id: '/_auth/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthContractsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/clients': {
      id: '/_auth/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthClientsRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/chat': {
      id: '/_auth/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AuthChatRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/about': {
      id: '/(marketing)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof marketingAboutRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/_auth/reviews/$id': {
      id: '/_auth/reviews/$id'
      path: '/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof AuthReviewsIdRouteImport
      parentRoute: typeof AuthReviewsRoute
    }
    '/_auth/matters_/$id': {
      id: '/_auth/matters_/$id'
      path: '/matters/$id'
      fullPath: '/matters/$id'
      preLoaderRoute: typeof AuthMattersIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/contracts_/$id': {
      id: '/_auth/contracts_/$id'
      path: '/contracts/$id'
      fullPath: '/contracts/$id'
      preLoaderRoute: typeof AuthContractsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface marketingRouteRouteChildren {
  marketingAboutRoute: typeof marketingAboutRoute
  marketingIndexRoute: typeof marketingIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingAboutRoute: marketingAboutRoute,
  marketingIndexRoute: marketingIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface AuthReviewsRouteChildren {
  AuthReviewsIdRoute: typeof AuthReviewsIdRoute
}

const AuthReviewsRouteChildren: AuthReviewsRouteChildren = {
  AuthReviewsIdRoute: AuthReviewsIdRoute,
}

const AuthReviewsRouteWithChildren = AuthReviewsRoute._addFileChildren(
  AuthReviewsRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthChatRoute: typeof AuthChatRoute
  AuthClientsRoute: typeof AuthClientsRoute
  AuthContractsRoute: typeof AuthContractsRoute
  AuthDocumentsRoute: typeof AuthDocumentsRoute
  AuthMattersRoute: typeof AuthMattersRoute
  AuthReviewsRoute: typeof AuthReviewsRouteWithChildren
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthWorkflowsRoute: typeof AuthWorkflowsRoute
  AuthContractsIdRoute: typeof AuthContractsIdRoute
  AuthMattersIdRoute: typeof AuthMattersIdRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthChatRoute: AuthChatRoute,
  AuthClientsRoute: AuthClientsRoute,
  AuthContractsRoute: AuthContractsRoute,
  AuthDocumentsRoute: AuthDocumentsRoute,
  AuthMattersRoute: AuthMattersRoute,
  AuthReviewsRoute: AuthReviewsRouteWithChildren,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthWorkflowsRoute: AuthWorkflowsRoute,
  AuthContractsIdRoute: AuthContractsIdRoute,
  AuthMattersIdRoute: AuthMattersIdRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface UnauthRouteRouteChildren {
  UnauthLoginRoute: typeof UnauthLoginRoute
  UnauthSignupRoute: typeof UnauthSignupRoute
}

const UnauthRouteRouteChildren: UnauthRouteRouteChildren = {
  UnauthLoginRoute: UnauthLoginRoute,
  UnauthSignupRoute: UnauthSignupRoute,
}

const UnauthRouteRouteWithChildren = UnauthRouteRoute._addFileChildren(
  UnauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  marketingRouteRoute: marketingRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  UnauthRouteRoute: UnauthRouteRouteWithChildren,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
