/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthRouteRouteImport } from './routes/_unauth/route'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as marketingRouteRouteImport } from './routes/(marketing)/route'
import { Route as marketingIndexRouteImport } from './routes/(marketing)/index'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as UnauthVerifyEmailRouteImport } from './routes/_unauth/verify-email'
import { Route as UnauthSignupRouteImport } from './routes/_unauth/signup'
import { Route as UnauthResetPasswordRouteImport } from './routes/_unauth/reset-password'
import { Route as UnauthLoginRouteImport } from './routes/_unauth/login'
import { Route as UnauthForgotPasswordRouteImport } from './routes/_unauth/forgot-password'
import { Route as DotwellKnownSplatRouteImport } from './routes/[.]well-known/$'
import { Route as marketingUseCasesRouteImport } from './routes/(marketing)/use-cases'
import { Route as marketingTermsRouteImport } from './routes/(marketing)/terms'
import { Route as marketingSecurityRouteImport } from './routes/(marketing)/security'
import { Route as marketingPrivacyRouteImport } from './routes/(marketing)/privacy'
import { Route as marketingAboutRouteImport } from './routes/(marketing)/about'
import { Route as AuthWorkflowsIndexRouteImport } from './routes/_auth/workflows/index'
import { Route as AuthSettingsIndexRouteImport } from './routes/_auth/settings/index'
import { Route as AuthReviewsIndexRouteImport } from './routes/_auth/reviews/index'
import { Route as AuthMattersIndexRouteImport } from './routes/_auth/matters/index'
import { Route as AuthDocumentsIndexRouteImport } from './routes/_auth/documents/index'
import { Route as AuthClientsIndexRouteImport } from './routes/_auth/clients/index'
import { Route as AuthAssistantIndexRouteImport } from './routes/_auth/assistant/index'
import { Route as marketingCompareIndexRouteImport } from './routes/(marketing)/compare.index'
import { Route as AuthReviewsIdRouteImport } from './routes/_auth/reviews/$id'
import { Route as AuthDocumentsIdRouteImport } from './routes/_auth/documents/$id'
import { Route as AuthAssistantIdRouteImport } from './routes/_auth/assistant/$id'
import { Route as marketingCompareSpellbookRouteImport } from './routes/(marketing)/compare.spellbook'
import { Route as marketingCompareLegalonRouteImport } from './routes/(marketing)/compare.legalon'
import { Route as marketingCompareLegalflyRouteImport } from './routes/(marketing)/compare.legalfly'
import { Route as marketingCompareHarveyRouteImport } from './routes/(marketing)/compare.harvey'
import { Route as marketingCompareGitlawRouteImport } from './routes/(marketing)/compare.gitlaw'
import { Route as AuthMattersIdIndexRouteImport } from './routes/_auth/matters/$id/index'
import { Route as AuthWorkflowsTabularReviewIdRouteImport } from './routes/_auth/workflows/tabular-review/$id'
import { Route as AuthWorkflowsAssistantIdRouteImport } from './routes/_auth/workflows/assistant/$id'
import { Route as AuthMattersIdAssistantIndexRouteImport } from './routes/_auth/matters/$id/assistant/index'
import { Route as AuthMattersIdAssistantChatIdRouteImport } from './routes/_auth/matters/$id/assistant/$chatId'

const UnauthRouteRoute = UnauthRouteRouteImport.update({
  id: '/_unauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingRouteRoute = marketingRouteRouteImport.update({
  id: '/(marketing)',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingIndexRoute = marketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthVerifyEmailRoute = UnauthVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const UnauthSignupRoute = UnauthSignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const UnauthResetPasswordRoute = UnauthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const UnauthLoginRoute = UnauthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const UnauthForgotPasswordRoute = UnauthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => UnauthRouteRoute,
} as any)
const DotwellKnownSplatRoute = DotwellKnownSplatRouteImport.update({
  id: '/.well-known/$',
  path: '/.well-known/$',
  getParentRoute: () => rootRouteImport,
} as any)
const marketingUseCasesRoute = marketingUseCasesRouteImport.update({
  id: '/use-cases',
  path: '/use-cases',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingTermsRoute = marketingTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingSecurityRoute = marketingSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingPrivacyRoute = marketingPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingAboutRoute = marketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => marketingRouteRoute,
} as any)
const AuthWorkflowsIndexRoute = AuthWorkflowsIndexRouteImport.update({
  id: '/workflows/',
  path: '/workflows/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSettingsIndexRoute = AuthSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthReviewsIndexRoute = AuthReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMattersIndexRoute = AuthMattersIndexRouteImport.update({
  id: '/matters/',
  path: '/matters/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDocumentsIndexRoute = AuthDocumentsIndexRouteImport.update({
  id: '/documents/',
  path: '/documents/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthClientsIndexRoute = AuthClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAssistantIndexRoute = AuthAssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const marketingCompareIndexRoute = marketingCompareIndexRouteImport.update({
  id: '/compare/',
  path: '/compare/',
  getParentRoute: () => marketingRouteRoute,
} as any)
const AuthReviewsIdRoute = AuthReviewsIdRouteImport.update({
  id: '/reviews/$id',
  path: '/reviews/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthDocumentsIdRoute = AuthDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthAssistantIdRoute = AuthAssistantIdRouteImport.update({
  id: '/assistant/$id',
  path: '/assistant/$id',
  getParentRoute: () => AuthRouteRoute,
} as any)
const marketingCompareSpellbookRoute =
  marketingCompareSpellbookRouteImport.update({
    id: '/compare/spellbook',
    path: '/compare/spellbook',
    getParentRoute: () => marketingRouteRoute,
  } as any)
const marketingCompareLegalonRoute = marketingCompareLegalonRouteImport.update({
  id: '/compare/legalon',
  path: '/compare/legalon',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingCompareLegalflyRoute =
  marketingCompareLegalflyRouteImport.update({
    id: '/compare/legalfly',
    path: '/compare/legalfly',
    getParentRoute: () => marketingRouteRoute,
  } as any)
const marketingCompareHarveyRoute = marketingCompareHarveyRouteImport.update({
  id: '/compare/harvey',
  path: '/compare/harvey',
  getParentRoute: () => marketingRouteRoute,
} as any)
const marketingCompareGitlawRoute = marketingCompareGitlawRouteImport.update({
  id: '/compare/gitlaw',
  path: '/compare/gitlaw',
  getParentRoute: () => marketingRouteRoute,
} as any)
const AuthMattersIdIndexRoute = AuthMattersIdIndexRouteImport.update({
  id: '/matters/$id/',
  path: '/matters/$id/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthWorkflowsTabularReviewIdRoute =
  AuthWorkflowsTabularReviewIdRouteImport.update({
    id: '/workflows/tabular-review/$id',
    path: '/workflows/tabular-review/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthWorkflowsAssistantIdRoute =
  AuthWorkflowsAssistantIdRouteImport.update({
    id: '/workflows/assistant/$id',
    path: '/workflows/assistant/$id',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthMattersIdAssistantIndexRoute =
  AuthMattersIdAssistantIndexRouteImport.update({
    id: '/matters/$id/assistant/',
    path: '/matters/$id/assistant/',
    getParentRoute: () => AuthRouteRoute,
  } as any)
const AuthMattersIdAssistantChatIdRoute =
  AuthMattersIdAssistantChatIdRouteImport.update({
    id: '/matters/$id/assistant/$chatId',
    path: '/matters/$id/assistant/$chatId',
    getParentRoute: () => AuthRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof marketingIndexRoute
  '/about': typeof marketingAboutRoute
  '/privacy': typeof marketingPrivacyRoute
  '/security': typeof marketingSecurityRoute
  '/terms': typeof marketingTermsRoute
  '/use-cases': typeof marketingUseCasesRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/forgot-password': typeof UnauthForgotPasswordRoute
  '/login': typeof UnauthLoginRoute
  '/reset-password': typeof UnauthResetPasswordRoute
  '/signup': typeof UnauthSignupRoute
  '/verify-email': typeof UnauthVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/compare/gitlaw': typeof marketingCompareGitlawRoute
  '/compare/harvey': typeof marketingCompareHarveyRoute
  '/compare/legalfly': typeof marketingCompareLegalflyRoute
  '/compare/legalon': typeof marketingCompareLegalonRoute
  '/compare/spellbook': typeof marketingCompareSpellbookRoute
  '/assistant/$id': typeof AuthAssistantIdRoute
  '/documents/$id': typeof AuthDocumentsIdRoute
  '/reviews/$id': typeof AuthReviewsIdRoute
  '/compare/': typeof marketingCompareIndexRoute
  '/assistant/': typeof AuthAssistantIndexRoute
  '/clients/': typeof AuthClientsIndexRoute
  '/documents/': typeof AuthDocumentsIndexRoute
  '/matters/': typeof AuthMattersIndexRoute
  '/reviews/': typeof AuthReviewsIndexRoute
  '/settings/': typeof AuthSettingsIndexRoute
  '/workflows/': typeof AuthWorkflowsIndexRoute
  '/workflows/assistant/$id': typeof AuthWorkflowsAssistantIdRoute
  '/workflows/tabular-review/$id': typeof AuthWorkflowsTabularReviewIdRoute
  '/matters/$id/': typeof AuthMattersIdIndexRoute
  '/matters/$id/assistant/$chatId': typeof AuthMattersIdAssistantChatIdRoute
  '/matters/$id/assistant/': typeof AuthMattersIdAssistantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof marketingIndexRoute
  '/about': typeof marketingAboutRoute
  '/privacy': typeof marketingPrivacyRoute
  '/security': typeof marketingSecurityRoute
  '/terms': typeof marketingTermsRoute
  '/use-cases': typeof marketingUseCasesRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/forgot-password': typeof UnauthForgotPasswordRoute
  '/login': typeof UnauthLoginRoute
  '/reset-password': typeof UnauthResetPasswordRoute
  '/signup': typeof UnauthSignupRoute
  '/verify-email': typeof UnauthVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/compare/gitlaw': typeof marketingCompareGitlawRoute
  '/compare/harvey': typeof marketingCompareHarveyRoute
  '/compare/legalfly': typeof marketingCompareLegalflyRoute
  '/compare/legalon': typeof marketingCompareLegalonRoute
  '/compare/spellbook': typeof marketingCompareSpellbookRoute
  '/assistant/$id': typeof AuthAssistantIdRoute
  '/documents/$id': typeof AuthDocumentsIdRoute
  '/reviews/$id': typeof AuthReviewsIdRoute
  '/compare': typeof marketingCompareIndexRoute
  '/assistant': typeof AuthAssistantIndexRoute
  '/clients': typeof AuthClientsIndexRoute
  '/documents': typeof AuthDocumentsIndexRoute
  '/matters': typeof AuthMattersIndexRoute
  '/reviews': typeof AuthReviewsIndexRoute
  '/settings': typeof AuthSettingsIndexRoute
  '/workflows': typeof AuthWorkflowsIndexRoute
  '/workflows/assistant/$id': typeof AuthWorkflowsAssistantIdRoute
  '/workflows/tabular-review/$id': typeof AuthWorkflowsTabularReviewIdRoute
  '/matters/$id': typeof AuthMattersIdIndexRoute
  '/matters/$id/assistant/$chatId': typeof AuthMattersIdAssistantChatIdRoute
  '/matters/$id/assistant': typeof AuthMattersIdAssistantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(marketing)': typeof marketingRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_unauth': typeof UnauthRouteRouteWithChildren
  '/(marketing)/about': typeof marketingAboutRoute
  '/(marketing)/privacy': typeof marketingPrivacyRoute
  '/(marketing)/security': typeof marketingSecurityRoute
  '/(marketing)/terms': typeof marketingTermsRoute
  '/(marketing)/use-cases': typeof marketingUseCasesRoute
  '/.well-known/$': typeof DotwellKnownSplatRoute
  '/_unauth/forgot-password': typeof UnauthForgotPasswordRoute
  '/_unauth/login': typeof UnauthLoginRoute
  '/_unauth/reset-password': typeof UnauthResetPasswordRoute
  '/_unauth/signup': typeof UnauthSignupRoute
  '/_unauth/verify-email': typeof UnauthVerifyEmailRoute
  '/api/$': typeof ApiSplatRoute
  '/(marketing)/': typeof marketingIndexRoute
  '/(marketing)/compare/gitlaw': typeof marketingCompareGitlawRoute
  '/(marketing)/compare/harvey': typeof marketingCompareHarveyRoute
  '/(marketing)/compare/legalfly': typeof marketingCompareLegalflyRoute
  '/(marketing)/compare/legalon': typeof marketingCompareLegalonRoute
  '/(marketing)/compare/spellbook': typeof marketingCompareSpellbookRoute
  '/_auth/assistant/$id': typeof AuthAssistantIdRoute
  '/_auth/documents/$id': typeof AuthDocumentsIdRoute
  '/_auth/reviews/$id': typeof AuthReviewsIdRoute
  '/(marketing)/compare/': typeof marketingCompareIndexRoute
  '/_auth/assistant/': typeof AuthAssistantIndexRoute
  '/_auth/clients/': typeof AuthClientsIndexRoute
  '/_auth/documents/': typeof AuthDocumentsIndexRoute
  '/_auth/matters/': typeof AuthMattersIndexRoute
  '/_auth/reviews/': typeof AuthReviewsIndexRoute
  '/_auth/settings/': typeof AuthSettingsIndexRoute
  '/_auth/workflows/': typeof AuthWorkflowsIndexRoute
  '/_auth/workflows/assistant/$id': typeof AuthWorkflowsAssistantIdRoute
  '/_auth/workflows/tabular-review/$id': typeof AuthWorkflowsTabularReviewIdRoute
  '/_auth/matters/$id/': typeof AuthMattersIdIndexRoute
  '/_auth/matters/$id/assistant/$chatId': typeof AuthMattersIdAssistantChatIdRoute
  '/_auth/matters/$id/assistant/': typeof AuthMattersIdAssistantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/use-cases'
    | '/.well-known/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/api/$'
    | '/compare/gitlaw'
    | '/compare/harvey'
    | '/compare/legalfly'
    | '/compare/legalon'
    | '/compare/spellbook'
    | '/assistant/$id'
    | '/documents/$id'
    | '/reviews/$id'
    | '/compare/'
    | '/assistant/'
    | '/clients/'
    | '/documents/'
    | '/matters/'
    | '/reviews/'
    | '/settings/'
    | '/workflows/'
    | '/workflows/assistant/$id'
    | '/workflows/tabular-review/$id'
    | '/matters/$id/'
    | '/matters/$id/assistant/$chatId'
    | '/matters/$id/assistant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/privacy'
    | '/security'
    | '/terms'
    | '/use-cases'
    | '/.well-known/$'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/verify-email'
    | '/api/$'
    | '/compare/gitlaw'
    | '/compare/harvey'
    | '/compare/legalfly'
    | '/compare/legalon'
    | '/compare/spellbook'
    | '/assistant/$id'
    | '/documents/$id'
    | '/reviews/$id'
    | '/compare'
    | '/assistant'
    | '/clients'
    | '/documents'
    | '/matters'
    | '/reviews'
    | '/settings'
    | '/workflows'
    | '/workflows/assistant/$id'
    | '/workflows/tabular-review/$id'
    | '/matters/$id'
    | '/matters/$id/assistant/$chatId'
    | '/matters/$id/assistant'
  id:
    | '__root__'
    | '/(marketing)'
    | '/_auth'
    | '/_unauth'
    | '/(marketing)/about'
    | '/(marketing)/privacy'
    | '/(marketing)/security'
    | '/(marketing)/terms'
    | '/(marketing)/use-cases'
    | '/.well-known/$'
    | '/_unauth/forgot-password'
    | '/_unauth/login'
    | '/_unauth/reset-password'
    | '/_unauth/signup'
    | '/_unauth/verify-email'
    | '/api/$'
    | '/(marketing)/'
    | '/(marketing)/compare/gitlaw'
    | '/(marketing)/compare/harvey'
    | '/(marketing)/compare/legalfly'
    | '/(marketing)/compare/legalon'
    | '/(marketing)/compare/spellbook'
    | '/_auth/assistant/$id'
    | '/_auth/documents/$id'
    | '/_auth/reviews/$id'
    | '/(marketing)/compare/'
    | '/_auth/assistant/'
    | '/_auth/clients/'
    | '/_auth/documents/'
    | '/_auth/matters/'
    | '/_auth/reviews/'
    | '/_auth/settings/'
    | '/_auth/workflows/'
    | '/_auth/workflows/assistant/$id'
    | '/_auth/workflows/tabular-review/$id'
    | '/_auth/matters/$id/'
    | '/_auth/matters/$id/assistant/$chatId'
    | '/_auth/matters/$id/assistant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  marketingRouteRoute: typeof marketingRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  UnauthRouteRoute: typeof UnauthRouteRouteWithChildren
  DotwellKnownSplatRoute: typeof DotwellKnownSplatRoute
  ApiSplatRoute: typeof ApiSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_unauth': {
      id: '/_unauth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof UnauthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)': {
      id: '/(marketing)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof marketingRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/': {
      id: '/(marketing)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof marketingIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_unauth/verify-email': {
      id: '/_unauth/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof UnauthVerifyEmailRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_unauth/signup': {
      id: '/_unauth/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof UnauthSignupRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_unauth/reset-password': {
      id: '/_unauth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof UnauthResetPasswordRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_unauth/login': {
      id: '/_unauth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof UnauthLoginRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/_unauth/forgot-password': {
      id: '/_unauth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof UnauthForgotPasswordRouteImport
      parentRoute: typeof UnauthRouteRoute
    }
    '/.well-known/$': {
      id: '/.well-known/$'
      path: '/.well-known/$'
      fullPath: '/.well-known/$'
      preLoaderRoute: typeof DotwellKnownSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(marketing)/use-cases': {
      id: '/(marketing)/use-cases'
      path: '/use-cases'
      fullPath: '/use-cases'
      preLoaderRoute: typeof marketingUseCasesRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/terms': {
      id: '/(marketing)/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof marketingTermsRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/security': {
      id: '/(marketing)/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof marketingSecurityRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/privacy': {
      id: '/(marketing)/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof marketingPrivacyRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/about': {
      id: '/(marketing)/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof marketingAboutRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/_auth/workflows/': {
      id: '/_auth/workflows/'
      path: '/workflows'
      fullPath: '/workflows/'
      preLoaderRoute: typeof AuthWorkflowsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/settings/': {
      id: '/_auth/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthSettingsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/reviews/': {
      id: '/_auth/reviews/'
      path: '/reviews'
      fullPath: '/reviews/'
      preLoaderRoute: typeof AuthReviewsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/matters/': {
      id: '/_auth/matters/'
      path: '/matters'
      fullPath: '/matters/'
      preLoaderRoute: typeof AuthMattersIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/documents/': {
      id: '/_auth/documents/'
      path: '/documents'
      fullPath: '/documents/'
      preLoaderRoute: typeof AuthDocumentsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/clients/': {
      id: '/_auth/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthClientsIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/assistant/': {
      id: '/_auth/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AuthAssistantIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(marketing)/compare/': {
      id: '/(marketing)/compare/'
      path: '/compare'
      fullPath: '/compare/'
      preLoaderRoute: typeof marketingCompareIndexRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/_auth/reviews/$id': {
      id: '/_auth/reviews/$id'
      path: '/reviews/$id'
      fullPath: '/reviews/$id'
      preLoaderRoute: typeof AuthReviewsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/documents/$id': {
      id: '/_auth/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof AuthDocumentsIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/assistant/$id': {
      id: '/_auth/assistant/$id'
      path: '/assistant/$id'
      fullPath: '/assistant/$id'
      preLoaderRoute: typeof AuthAssistantIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/(marketing)/compare/spellbook': {
      id: '/(marketing)/compare/spellbook'
      path: '/compare/spellbook'
      fullPath: '/compare/spellbook'
      preLoaderRoute: typeof marketingCompareSpellbookRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/compare/legalon': {
      id: '/(marketing)/compare/legalon'
      path: '/compare/legalon'
      fullPath: '/compare/legalon'
      preLoaderRoute: typeof marketingCompareLegalonRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/compare/legalfly': {
      id: '/(marketing)/compare/legalfly'
      path: '/compare/legalfly'
      fullPath: '/compare/legalfly'
      preLoaderRoute: typeof marketingCompareLegalflyRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/compare/harvey': {
      id: '/(marketing)/compare/harvey'
      path: '/compare/harvey'
      fullPath: '/compare/harvey'
      preLoaderRoute: typeof marketingCompareHarveyRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/(marketing)/compare/gitlaw': {
      id: '/(marketing)/compare/gitlaw'
      path: '/compare/gitlaw'
      fullPath: '/compare/gitlaw'
      preLoaderRoute: typeof marketingCompareGitlawRouteImport
      parentRoute: typeof marketingRouteRoute
    }
    '/_auth/matters/$id/': {
      id: '/_auth/matters/$id/'
      path: '/matters/$id'
      fullPath: '/matters/$id/'
      preLoaderRoute: typeof AuthMattersIdIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/workflows/tabular-review/$id': {
      id: '/_auth/workflows/tabular-review/$id'
      path: '/workflows/tabular-review/$id'
      fullPath: '/workflows/tabular-review/$id'
      preLoaderRoute: typeof AuthWorkflowsTabularReviewIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/workflows/assistant/$id': {
      id: '/_auth/workflows/assistant/$id'
      path: '/workflows/assistant/$id'
      fullPath: '/workflows/assistant/$id'
      preLoaderRoute: typeof AuthWorkflowsAssistantIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/matters/$id/assistant/': {
      id: '/_auth/matters/$id/assistant/'
      path: '/matters/$id/assistant'
      fullPath: '/matters/$id/assistant/'
      preLoaderRoute: typeof AuthMattersIdAssistantIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_auth/matters/$id/assistant/$chatId': {
      id: '/_auth/matters/$id/assistant/$chatId'
      path: '/matters/$id/assistant/$chatId'
      fullPath: '/matters/$id/assistant/$chatId'
      preLoaderRoute: typeof AuthMattersIdAssistantChatIdRouteImport
      parentRoute: typeof AuthRouteRoute
    }
  }
}

interface marketingRouteRouteChildren {
  marketingAboutRoute: typeof marketingAboutRoute
  marketingPrivacyRoute: typeof marketingPrivacyRoute
  marketingSecurityRoute: typeof marketingSecurityRoute
  marketingTermsRoute: typeof marketingTermsRoute
  marketingUseCasesRoute: typeof marketingUseCasesRoute
  marketingIndexRoute: typeof marketingIndexRoute
  marketingCompareGitlawRoute: typeof marketingCompareGitlawRoute
  marketingCompareHarveyRoute: typeof marketingCompareHarveyRoute
  marketingCompareLegalflyRoute: typeof marketingCompareLegalflyRoute
  marketingCompareLegalonRoute: typeof marketingCompareLegalonRoute
  marketingCompareSpellbookRoute: typeof marketingCompareSpellbookRoute
  marketingCompareIndexRoute: typeof marketingCompareIndexRoute
}

const marketingRouteRouteChildren: marketingRouteRouteChildren = {
  marketingAboutRoute: marketingAboutRoute,
  marketingPrivacyRoute: marketingPrivacyRoute,
  marketingSecurityRoute: marketingSecurityRoute,
  marketingTermsRoute: marketingTermsRoute,
  marketingUseCasesRoute: marketingUseCasesRoute,
  marketingIndexRoute: marketingIndexRoute,
  marketingCompareGitlawRoute: marketingCompareGitlawRoute,
  marketingCompareHarveyRoute: marketingCompareHarveyRoute,
  marketingCompareLegalflyRoute: marketingCompareLegalflyRoute,
  marketingCompareLegalonRoute: marketingCompareLegalonRoute,
  marketingCompareSpellbookRoute: marketingCompareSpellbookRoute,
  marketingCompareIndexRoute: marketingCompareIndexRoute,
}

const marketingRouteRouteWithChildren = marketingRouteRoute._addFileChildren(
  marketingRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthAssistantIdRoute: typeof AuthAssistantIdRoute
  AuthDocumentsIdRoute: typeof AuthDocumentsIdRoute
  AuthReviewsIdRoute: typeof AuthReviewsIdRoute
  AuthAssistantIndexRoute: typeof AuthAssistantIndexRoute
  AuthClientsIndexRoute: typeof AuthClientsIndexRoute
  AuthDocumentsIndexRoute: typeof AuthDocumentsIndexRoute
  AuthMattersIndexRoute: typeof AuthMattersIndexRoute
  AuthReviewsIndexRoute: typeof AuthReviewsIndexRoute
  AuthSettingsIndexRoute: typeof AuthSettingsIndexRoute
  AuthWorkflowsIndexRoute: typeof AuthWorkflowsIndexRoute
  AuthWorkflowsAssistantIdRoute: typeof AuthWorkflowsAssistantIdRoute
  AuthWorkflowsTabularReviewIdRoute: typeof AuthWorkflowsTabularReviewIdRoute
  AuthMattersIdIndexRoute: typeof AuthMattersIdIndexRoute
  AuthMattersIdAssistantChatIdRoute: typeof AuthMattersIdAssistantChatIdRoute
  AuthMattersIdAssistantIndexRoute: typeof AuthMattersIdAssistantIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthAssistantIdRoute: AuthAssistantIdRoute,
  AuthDocumentsIdRoute: AuthDocumentsIdRoute,
  AuthReviewsIdRoute: AuthReviewsIdRoute,
  AuthAssistantIndexRoute: AuthAssistantIndexRoute,
  AuthClientsIndexRoute: AuthClientsIndexRoute,
  AuthDocumentsIndexRoute: AuthDocumentsIndexRoute,
  AuthMattersIndexRoute: AuthMattersIndexRoute,
  AuthReviewsIndexRoute: AuthReviewsIndexRoute,
  AuthSettingsIndexRoute: AuthSettingsIndexRoute,
  AuthWorkflowsIndexRoute: AuthWorkflowsIndexRoute,
  AuthWorkflowsAssistantIdRoute: AuthWorkflowsAssistantIdRoute,
  AuthWorkflowsTabularReviewIdRoute: AuthWorkflowsTabularReviewIdRoute,
  AuthMattersIdIndexRoute: AuthMattersIdIndexRoute,
  AuthMattersIdAssistantChatIdRoute: AuthMattersIdAssistantChatIdRoute,
  AuthMattersIdAssistantIndexRoute: AuthMattersIdAssistantIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface UnauthRouteRouteChildren {
  UnauthForgotPasswordRoute: typeof UnauthForgotPasswordRoute
  UnauthLoginRoute: typeof UnauthLoginRoute
  UnauthResetPasswordRoute: typeof UnauthResetPasswordRoute
  UnauthSignupRoute: typeof UnauthSignupRoute
  UnauthVerifyEmailRoute: typeof UnauthVerifyEmailRoute
}

const UnauthRouteRouteChildren: UnauthRouteRouteChildren = {
  UnauthForgotPasswordRoute: UnauthForgotPasswordRoute,
  UnauthLoginRoute: UnauthLoginRoute,
  UnauthResetPasswordRoute: UnauthResetPasswordRoute,
  UnauthSignupRoute: UnauthSignupRoute,
  UnauthVerifyEmailRoute: UnauthVerifyEmailRoute,
}

const UnauthRouteRouteWithChildren = UnauthRouteRoute._addFileChildren(
  UnauthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  marketingRouteRoute: marketingRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  UnauthRouteRoute: UnauthRouteRouteWithChildren,
  DotwellKnownSplatRoute: DotwellKnownSplatRoute,
  ApiSplatRoute: ApiSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
