// Embedded deployment files. Written into GITMATTER_HOME on `init` so the
// compiled binary is self-contained — the user never authors YAML.

/** Base stack: Caddy (TLS + LAN entry), web app. */
export const COMPOSE_BASE = `# Generated by gitmatter. Do not edit by hand — re-run \`gitmatter init\`.
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

  # One-shot schema migration. Runs to completion before web starts; keeps the
  # serving container immutable (no schema mutation at app boot).
  migrate:
    image: \${GITMATTER_IMAGE:-ghcr.io/peteqian/gitmatter:latest}
    restart: "no"
    environment:
      DATABASE_URL: \${DATABASE_URL}
    command: ["sh", "-c", "cd /app/packages/db && bun run migrate"]

  web:
    image: \${GITMATTER_IMAGE:-ghcr.io/peteqian/gitmatter:latest}
    restart: unless-stopped
    depends_on:
      migrate:
        condition: service_completed_successfully
    environment:
      DATABASE_URL: \${DATABASE_URL}
      BETTER_AUTH_SECRET: \${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: \${BETTER_AUTH_URL}
      ENCRYPTION_KEY: \${ENCRYPTION_KEY}
      COURTLISTENER_API_TOKEN: \${COURTLISTENER_API_TOKEN:-}
      PORT: "4280"
    expose:
      - "4280"

volumes:
  caddy_data:
  caddy_config:
`;

/** Overlay applied only when the user picks the bundled database. */
export const COMPOSE_DB = `# Generated by gitmatter. Bundled-Postgres overlay.
services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-gitmatter}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-gitmatter}
      POSTGRES_DB: \${POSTGRES_DB:-gitmatter}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-gitmatter}"]
      interval: 5s
      timeout: 5s
      retries: 10

  # Bundled DB: the migration step waits for Postgres to be healthy.
  migrate:
    depends_on:
      postgres:
        condition: service_healthy

  web:
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
`;

/**
 * Render the Caddyfile for a domain + TLS mode.
 * - "internal": Caddy's own CA. Works on LAN / .local with no public DNS, but
 *   browsers warn until the user trusts the root CA (`gitmatter doctor` prints
 *   the install step).
 * - "auto": real ACME cert. Needs a public domain that resolves to this host.
 */
export function renderCaddyfile(domain: string, tls: "internal" | "auto"): string {
  const tlsLine = tls === "internal" ? "\n    tls internal" : "";
  return `# Generated by gitmatter. Re-run \`gitmatter init\` to change.
${domain} {
    reverse_proxy web:4280${tlsLine}
}
`;
}
