// Embedded deployment files. Written into GITCOUNSEL_HOME on `init` so the
// compiled binary is self-contained — the user never authors YAML.

/** Base stack: Caddy (TLS + LAN entry), docling sidecar, web app. */
export const COMPOSE_BASE = `# Generated by gitcounsel. Do not edit by hand — re-run \`gitcounsel init\`.
services:
  caddy:
    image: caddy:2
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - web

  # Docling document parser as a sidecar. No auth -> internal network only.
  docling:
    image: quay.io/docling-project/docling-serve-cpu:latest
    restart: unless-stopped
    expose:
      - "5001"

  web:
    image: \${GITCOUNSEL_IMAGE:-ghcr.io/gitcounsel/gitcounsel:latest}
    restart: unless-stopped
    depends_on:
      docling:
        condition: service_started
    environment:
      DATABASE_URL: \${DATABASE_URL}
      BETTER_AUTH_SECRET: \${BETTER_AUTH_SECRET}
      BETTER_AUTH_URL: \${BETTER_AUTH_URL}
      ENCRYPTION_KEY: \${ENCRYPTION_KEY}
      COURTLISTENER_API_TOKEN: \${COURTLISTENER_API_TOKEN:-}
      DOCLING_URL: http://docling:5001/v1/convert/source
      PORT: "4280"
    expose:
      - "4280"

volumes:
  caddy_data:
  caddy_config:
`;

/** Overlay applied only when the user picks the bundled database. */
export const COMPOSE_DB = `# Generated by gitcounsel. Bundled-Postgres overlay.
services:
  postgres:
    image: pgvector/pgvector:pg17
    restart: unless-stopped
    environment:
      POSTGRES_USER: \${POSTGRES_USER:-gitcounsel}
      POSTGRES_PASSWORD: \${POSTGRES_PASSWORD:-gitcounsel}
      POSTGRES_DB: \${POSTGRES_DB:-gitcounsel}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U \${POSTGRES_USER:-gitcounsel}"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  pgdata:
`;

/**
 * Render the Caddyfile for a domain + TLS mode.
 * - "internal": Caddy's own CA. Works on LAN / .local with no public DNS, but
 *   browsers warn until the user trusts the root CA (`gitcounsel doctor` prints
 *   the install step).
 * - "auto": real ACME cert. Needs a public domain that resolves to this host.
 */
export function renderCaddyfile(domain: string, tls: "internal" | "auto"): string {
  const tlsLine = tls === "internal" ? "\n    tls internal" : "";
  return `# Generated by gitcounsel. Re-run \`gitcounsel init\` to change.
${domain} {
    reverse_proxy web:4280${tlsLine}
}
`;
}
